spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        username: lamisplus_etl
        password: zleMUuPjLN36cYs
        url: jdbc:postgresql://localhost:5432/lamisplus_ods_dwh
        hibernate:
            ddl-auto: none
            event.merge.entry_copy_observer: allow
        hikari:
            auto-commit: true
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
            maximum-pool-size: 20
            minimum-idle: 5
    jpa:
        database: POSTGRESQL
        show-sql: false
        open-in-view: false
        properties:
            hibernate.enable_lazy_load_no_trans: true
server:
    port: 7355