spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        username: postgres
        password: emeka
        url: jdbc:postgresql://localhost:5432/radet-generation
        hibernate:
            ddl-auto: none
            event.merge.entry_copy_observer: allow
        hikari:
            auto-commit: true
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
            maximum-pool-size: 20
            minimum-idle: 5
    jpa:
        database: POSTGRESQL
        show-sql: false
        open-in-view: false
        properties:
            hibernate.enable_lazy_load_no_trans: true
server:
    port: 8585
lamisplus:
    report:
        radet: d81f58f6-8361-45cc-9564-b2e9a5d17eea
        prep: 45f01feb-227b-4740-9e0a-882fea830ec0
        hts: bed8af69-4eef-4420-9591-7b783bac2792